version: '3'

networks: 
  my-net:
    

services:
  sqldb:
    build: ./sql
    ports:
      - 3306:3306
    networks:
      - my-net
    container_name: sql1

  sqlinitiate:
    build: ./gosql
    ports:
      - 8080:8080
    networks:
      - my-net
    depends_on:
      - sqldb

  goweb:
    build: ./goweb
    ports:
      - 8080:8080
    networks:
      - my-net
    depends_on:
      - sqlinitiate
    command: ["./wait-for-it.sh", "localhost:8080", "-s", "docker", "run", "-p", "8080:8080", "--network=my-net", "./goweb"]
    



