version: '3'

networks: 
  my-net:
    

services:
  sqldb:
    build: ./sql
    ports:
      - 3306:3306
    networks:
      - my-net
    container_name: sql1

  sqlinitiate:
    build: ./gosql
    ports:
      - 8080:8080
    networks:
      - my-net
    depends_on:
      - sqldb
    command: >
      /bin/bash -c "
        sleep 5;
      "


